src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book extends Document
{
    /**
     * @ORM\Column(type="integer")
     */
    #[Assert\LessThan(2001, null, 'please its too big')]
    #[Assert\GreaterThan(100000, null, 'please its too small')]
    private $nb_page;

    public function getNbPage(): ?int
    {
        return $this->nb_page;
    }

    public function setNbPage(int $nb_page): self
    {
        $this->nb_page = $nb_page;

        return $this;
    }
}

templates/back-office/book_form/_delete_form.html.twig
<form
  method="post"
  action="{{ path('book_delete', { id: book.id }) }}"
  onsubmit="return confirm('Are you sure you want to delete this item?');"
>
  <input
    type="hidden"
    name="_token"
    value="{{ csrf_token('delete' ~ book.id) }}"
  />
  <button class="btn">Delete</button>
</form>

templates/back-office/book_form/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/back-office/book_form/edit.html.twig
{% extends 'back-office/base.html.twig' %} {% block title %}Admin panel{%
endblock %} {% block body %}
<h1>Edit Book</h1>

{{ include('back-office/book/_form.html.twig', { button_label: 'Update' }) }}

<a href="{{ path('book_form_index') }}">back to list</a>

{{ include('back-office/book/_delete_form.html.twig') }}
{% endblock %}

templates/back-office/book_form/index.html.twig
{% extends 'back-office/base.html.twig' %} {% block title %}Admin panel{%
endblock %} {% block body %}
<h1>Book index</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Code</th>
      <th>Nb_page</th>
      <th>actions</th>
    </tr>
  </thead>
  <tbody>
    {% for book in books %}
    <tr>
      <td>{{ book.id }}</td>
      <td>{{ book.title }}</td>
      <td>{{ book.code }}</td>
      <td>{{ book.nbPage }}</td>
      <td>
        <a href="{{ path('book_form_show', { id: book.id }) }}">show</a>
        <a href="{{ path('book_form_edit', { id: book.id }) }}">edit</a>
      </td>
    </tr>
    {% else %}
    <tr>
      <td colspan="5">no records found</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{{ path('book_form_new') }}">Create new</a>
{% endblock %}

templates/back-office/book_form/new.html.twig
{% extends 'back-office/base.html.twig' %} {% block title %}Admin panel{%
endblock %} {% block body %}
<h1>Create new Book</h1>

{{ include('back-office/book/_form.html.twig') }}

<a href="{{ path('book_form_index') }}">back to list</a>
{% endblock %}

templates/back-office/book_form/show.html.twig
{% extends 'back-office/base.html.twig' %} {% block title %}Admin panel{%
endblock %} {% block body %}
<h1>Book</h1>

<table class="table">
  <tbody>
    <tr>
      <th>Id</th>
      <td>{{ book.id }}</td>
    </tr>
    <tr>
      <th>Title</th>
      <td>{{ book.title }}</td>
    </tr>
    <tr>
      <th>Code</th>
      <td>{{ book.code }}</td>
    </tr>
    <tr>
      <th>Nb_page</th>
      <td>{{ book.nbPage }}</td>
    </tr>
  </tbody>
</table>

<a href="{{ path('book_form_index') }}">back to list</a>

<a href="{{ path('book_form_edit', { id: book.id }) }}">edit</a>

{{ include('back-office/book/_delete_form.html.twig') }}
{% endblock %}